'use client';
import {useEffect,useMemo,useState} from 'react';
import Player from './components/Player';

type Item={id:string;name:string;stream:string;logo?:string;category?:string;type?:'live'|'movie'|'series';extension?:string};
type Data={user?:string;categories:string[];channels:Item[];movies:Item[];series:Item[];session?:any};
type Tab='live'|'movies'|'series'|'favorites';

export default function Home(){
 const [mode,setMode]=useState<'xtream'|'m3u'>('xtream'); const [server,setServer]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [m3u,setM3u]=useState('');
 const [data,setData]=useState<Data|null>(null); const [selected,setSelected]=useState<Item|null>(null); const [tab,setTab]=useState<Tab>('live'); const [category,setCategory]=useState('All'); const [query,setQuery]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [favorites,setFavorites]=useState<string[]>([]); const [history,setHistory]=useState<Item[]>([]); const [epg,setEpg]=useState<any[]>([]); const [seriesInfo,setSeriesInfo]=useState<any|null>(null);
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem('sd:favorites')||'[]'));setHistory(JSON.parse(localStorage.getItem('sd:history')||'[]'));}catch{}} ,[]);
 useEffect(()=>{localStorage.setItem('sd:favorites',JSON.stringify(favorites))},[favorites]); useEffect(()=>{localStorage.setItem('sd:history',JSON.stringify(history.slice(0,20)))},[history]);
 const connect=async()=>{setError('');setLoading(true);try{const payload=mode==='m3u'?{mode,m3u}:{mode,server,username,password};const r=await fetch('/api/xtream',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to connect');setData(j);setSelected(j.channels?.[0]||j.movies?.[0]||j.series?.[0]||null);setTab('live');setCategory('All');}catch(e:any){setError(e.message||'Connection failed')}finally{setLoading(false)}};
 const allForTab=useMemo(()=>{if(!data)return []; if(tab==='live')return data.channels; if(tab==='movies')return data.movies; if(tab==='series')return data.series; const all=[...data.channels,...data.movies,...data.series]; return all.filter(x=>favorites.includes(`${x.type}:${x.id}`));},[data,tab,favorites]);
 const categories=useMemo(()=>tab==='live'?(data?.categories||[]):[...new Set(allForTab.map(x=>x.category).filter(Boolean) as string[])],[data,tab,allForTab]);
 const filtered=useMemo(()=>allForTab.filter(x=>(category==='All'||x.category===category)&&x.name.toLowerCase().includes(query.toLowerCase())),[allForTab,category,query]);
 const pick=(item:Item)=>{setSelected(item);setSeriesInfo(null);if(item.type!=='series'){setHistory(h=>[item,...h.filter(x=>x.id!==item.id||x.type!==item.type)].slice(0,20));if(item.type==='live'&&data?.session?.mode==='xtream')fetchEpg(item.id)}else if(data?.session?.mode==='xtream')fetchSeries(item.id)};
 const toggleFav=(item:Item)=>setFavorites(f=>f.includes(`${item.type}:${item.id}`)?f.filter(k=>k!==`${item.type}:${item.id}`):[...f,`${item.type}:${item.id}`]);
 const fetchEpg=async(id:string)=>{if(!data?.session?.server)return;try{const r=await fetch('/api/xtream',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...data.session,action:'epg',id})});const j=await r.json();setEpg(j?.epg_listings||[])}catch{setEpg([])}};
 const fetchSeries=async(id:string)=>{if(!data?.session?.server)return;try{const r=await fetch('/api/xtream',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...data.session,action:'series_info',id})});const j=await r.json();setSeriesInfo(j)}catch{setSeriesInfo(null)}};
 if(data)return <main className="shell"><div className="nav"><div className="brand">MMN <span>OTT MART</span></div><div className="navright"><span className="muted">{data.user}</span><button className="tab" onClick={()=>{setData(null);setSelected(null);setEpg([]);setSeriesInfo(null)}}>Disconnect</button></div></div><div className="dashboard"><aside className="side"><h3>Library</h3>{(['live','movies','series','favorites'] as Tab[]).map(t=><button key={t} className={'cat '+(tab===t?'selected':'')} onClick={()=>{setTab(t);setCategory('All');setQuery('')}}>{t==='live'?'Live TV':t[0].toUpperCase()+t.slice(1)}</button>)}{history.length>0&&<><h3>Continue Watching</h3>{history.slice(0,5).map(x=><button key={x.type+x.id} className="cat" onClick={()=>pick(x)}>{x.name}</button>)}</>}<h3>Categories</h3><button className={'cat '+(category==='All'?'selected':'')} onClick={()=>setCategory('All')}>All</button>{categories.slice(0,40).map(c=><button className={'cat '+(category===c?'selected':'')} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</aside><section><div className="toolbar"><input className="search" placeholder="Search channels, movies or series…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Player src={selected?.stream||''}/><div className="topline"><div><h2>{selected?.name||'Select something to watch'}</h2><span className="muted">{selected?.category||'Choose a title below'}</span></div>{selected&&<button className="fav" onClick={()=>toggleFav(selected)}>{favorites.includes(`${selected.type}:${selected.id}`)?'★ Saved':'☆ Save'}</button>}</div>{seriesInfo&&<div className="episodes"><h3>Episodes</h3>{Object.entries(seriesInfo.episodes||{}).map(([season,eps]:any)=><div key={season}><b>Season {season}</b><div className="episodegrid">{(eps||[]).map((e:any)=><button key={e.id} onClick={()=>pick({id:String(e.id),name:`S${season}E${e.episode_num} · ${e.title||'Episode'}`,stream:`/api/stream?url=${encodeURIComponent(`${data.session.server}/series/${encodeURIComponent(data.session.username)}/${encodeURIComponent(data.session.password)}/${e.id}.${e.container_extension||'mp4'}`)}`,type:'movie'})}>{e.episode_num}. {e.title||'Episode'}</button>)}</div></div>)}</div>}{epg.length>0&&tab==='live'&&<div className="epg"><h3>TV Guide</h3>{epg.slice(0,8).map((x:any,i:number)=><div className="epgrow" key={i}><span>{x.start||''}</span><b>{x.title||'Program'}</b><small>{x.description||''}</small></div>)}</div>}<div className="channels">{filtered.slice(0,120).map(c=><button className={'channel '+(selected?.id===c.id&&selected?.type===c.type?'active':'')} key={c.type+c.id} onClick={()=>pick(c)}>{c.logo?<img src={c.logo} alt=""/>:<span className="logoPlaceholder">{c.name.slice(0,1)}</span>}<span>{c.name}</span><small>{c.category||c.type}</small></button>)}</div>{filtered.length===0&&<div className="empty">Nothing matches your search or filter.</div>}</section></div></main>;
 return <main className="shell"><div className="nav"><div className="brand">MMN <span>OTT MART</span></div><span className="muted">Secure browser player</span></div><section className="hero"><div className="eyebrow">WEB PLAYER · NO APP INSTALLATION</div><h1>Watch your subscription.<br/>Directly in Chrome.</h1><p>Having trouble finding your usual IPTV app in the UK, USA, or another country? Sign in with the subscription credentials provided to you and watch compatible Live TV, Movies and Series from your browser.</p></section><section className="card"><div className="tabs"><button className={'tab '+(mode==='xtream'?'active':'')} onClick={()=>setMode('xtream')}>Subscription Login</button><button className={'tab '+(mode==='m3u'?'active':'')} onClick={()=>setMode('m3u')}>Playlist URL</button></div>{mode==='xtream'?<div className="grid"><div className="field wide"><label>Server URL provided with your subscription</label><input placeholder="http://provider.example:8080" value={server} onChange={e=>setServer(e.target.value)}/></div><div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div></div>:<div className="field"><label>M3U / M3U8 URL</label><input placeholder="https://provider.example/playlist.m3u8" value={m3u} onChange={e=>setM3u(e.target.value)}/></div>}<div className="actions"><button className="primary" disabled={loading||(!server&&!m3u)} onClick={connect}>{loading?'Signing in…':'Sign In & Watch'}</button></div>{error&&<div className="error">{error}</div>}<div className="trust"><span>🔒</span><div><b>Your credentials are used only to connect your authorized subscription.</b><small>Playback depends on the subscription provider, browser compatibility, and any geographic or network restrictions.</small></div></div></section></main>;
}
